---
- name: Home work 3 - Deploy Monitoring Stack (Prometheus + Grafana)
  hosts: carrier
  become: true
  vars:
    monitoring_config_dir: /opt/monitoring
    monitoring_network: wp-network
    prometheus_image: "prom/prometheus:v3.4.1"
    prometheus_port: 9090
    grafana_image: "grafana/grafana:12.0.2"
    grafana_port: 3000
    grafana_data_dir: "{{ monitoring_config_dir }}/grafana_data"
    grafana_admin_password: "admin"
  tasks:
    - name: Ensure monitoring directories exist
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        mode: '0755'
        owner: "{{ item.owner | default(omit) }}"
        group: "{{ item.group | default(omit) }}"
      loop:
        - { path: "{{ monitoring_config_dir }}" }
        - { path: "{{ grafana_data_dir }}", owner: '472', group: '472' }
        
    - name: Create directories for monitoring stack (Prometheus)
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - /srv/docker/prometheus
        - /srv/docker/grafana/provisioning/datasources

    - name: Deploy Prometheus configuration from template
      ansible.builtin.template:
        src: templates/prometheus.yml.j2
        dest: "{{ monitoring_config_dir }}/prometheus.yml"
        mode: '0644'
      notify:
        - Restart prometheus container

    - name: Run Prometheus container
      community.docker.docker_container:
        name: prometheus
        image: "{{ prometheus_image }}"
        state: started
        restart_policy: unless-stopped
        pull: true
        published_ports:
          - "{{ prometheus_port }}:{{ prometheus_port }}"
        volumes:
          - "{{ monitoring_config_dir }}/prometheus.yml:/etc/prometheus/prometheus.yml"
        networks:
          - name: "{{ monitoring_network }}"
    
    - name: Run Grafana container
      community.docker.docker_container:
        name: grafana
        image: "{{ grafana_image }}"
        state: started
        restart_policy: unless-stopped
        pull: true
        published_ports:
          - "{{ grafana_port }}:3000"
        volumes:
          - "{{ grafana_data_dir }}:/var/lib/grafana"
        networks:
          - name: "{{ monitoring_network }}"
    
    - name: Wait for Grafana to be ready
      ansible.builtin.wait_for:
        host: "127.0.0.1"
        port: 3000
        state: started
        delay: 10
        timeout: 300
      run_once: true

    - name: Show monitoring access info
      ansible.builtin.debug:
        msg:
          - "Prometheus URL: http://{{ ansible_host }}:9090"
          - "Grafana URL: http://{{ ansible_host }}:3000  (Login: admin/admin)"

  handlers:
    - name: Restart prometheus container
      community.docker.docker_container:
        name: prometheus
        state: started
        restart: true
